### ISSUE TITLE
[sway] Memory access error (memory dumped)

### ISSUE THREAD

**Issue by jdbm8992** [GhostNaN/mpvpaper#1]
Installation: mpvpaper was installed from the AUR
Version: mpvpaper-git-r8.4927e4e-1
WM: sway v1.5
CPU / GPU: Intel Core i5-2450M / Intel HD 3000
Used RAM: 3044MiB / 7889MiB

Steps to reproduce:

1. `killall swaybg`
2. `mpvpaper LVDS-1 MyVideoWallpaper.mp4`

strace output (last 12 lines (looks like less because of bad formatting)):

`ioctl(5, DRM_IOCTL_I915_GEM_CONTEXT_SETPARAM, 0x7ffdd029dcc0) = -1 ENODEV (No such device)
ioctl(5, DRM_IOCTL_I915_GEM_CONTEXT_SETPARAM, 0x7ffdd029dcc0) = -1 ENODEV (No such device)
ioctl(5, DRM_IOCTL_I915_GEM_CONTEXT_SETPARAM, 0x7ffdd029dcc0) = -1 ENODEV (No such device)
getpid()                                = 197484
getpid()                                = 197484
getpid()                                = 197484
mincore(NULL, 4096, 0x7ffdd029de27)     = -1 ENOMEM (Cannot allocate memory)
getpid()                                = 197484
getpid()                                = 197484
getpid()                                = 197484
--- SIGSEGV {si_signo=SIGSEGV, si_code=SEGV_MAPERR, si_addr=NULL} ---
+++ killed by SIGSEGV (core dumped) +++`

**Comment by GhostNaN** [comment]
I believe your GPU doesn't support OpenGL 4.6 that I put in. 

https://www.intel.com/content/www/us/en/support/articles/000005524/graphics.html

I made a new branch "opengl-3.0" for you to try: https://github.com/GhostNaN/mpvpaper/tree/opengl-3.0

Follow the build instructions, but instead of:
```
git clone --single-branch https://github.com/GhostNaN/mpvpaper
```
Do:
```
git clone --single-branch --branch opengl-3.0 https://github.com/GhostNaN/mpvpaper
```
Then follow the rest.

**Comment by jdbm8992** [comment]
It works now :smile:! Thank you very much @GhostNaN ! Really cool project....Keep it up!

**Comment by marb** [comment]
I have the same issue and some semi-ancient hardware. Can you make OpenGL 4.3 branch?

Intel i7-3740QM
glxinfo
OpenGL version string: 4.3 (Compatibility Profile) Mesa 21.1.4

**Comment by marb** [comment]
Yeah. Looks like something else.

mpvpaper -v LVDS-1 video.mp4
[*] Output LVDS-1 (Unknown 0x0338 0x00000000) selected
[*] OpenGL 3.3 EGL context loaded
Memory access error (memory dumped)

**Comment by GhostNaN** [comment]
OpenGL must not be initializing...

It might be a long shot, but the OpenGL profile this comes with is "Core".
Down below is mpvpaper, but with the "Compatiblity" profile instead:
[mpvpaper.tar.gz](https://github.com/GhostNaN/mpvpaper/files/6835230/mpvpaper.tar.gz)

Build, then run and see if it works for you.

**Comment by marb** [comment]
It's giving me the same result.

**Comment by GhostNaN** [comment]
Then I don't know. 

My laptop has similar specs to yours with a i7 3840QM. So I don't think it's a hardware compatibility issue.
It might be just your particular system with it's set of software.

Well if you feel like debugging yourself with gdb or something else, let me know what you find. 
Either way thanks for trying.
