### ISSUE TITLE
Second instance does not obey 'loop' mpv option

### ISSUE THREAD

**Issue by kquote03** [GhostNaN/mpvpaper#15]
When running two instances of mpvpaper (eg for a dual monitor setup), the second instance does not loop and quits after the video is done.
Can either be done when specifying mpvpaper twice in sway config, or running two mpvpaper instances at the same time in the same shell.
Exact command (for my setup) `exec mpvpaper -o "no-audio loop  --hwdec=vaapi" eDP-1 "Outerwall.m4v" & exec mpvpaper -o "no-audio loop  --hwdec=vaapi" HDMI-A-1 "Outerwall.m4v"`

**Comment by GhostNaN** [comment]
I hope that solves that. Let me know!

**Comment by kquote03** [comment]
Oh wow, that was quick, it works fine now! Thank you very much!!
