### ISSUE TITLE
steam wallpaper  engine compatibility

### ISSUE THREAD

**Issue by Iss-in** [GhostNaN/mpvpaper#27]
hey, First off thanks for the awesome work :)

 am much clear on whether this is even possible, but is there a chance your work can be integrated in https://github.com/catsout/wallpaper-engine-kde-plugin as well 

will be awesome if this could happen

**Comment by GhostNaN** [comment]
I'm not really sure what you're asking here.
That project already has optional support for mpv.

**Comment by GhostNaN** [comment]
I'm closing this issue for now because I'm assuming you were asking for mpv support for a KDE plugin that already has it.
If this is not correct, feel free to reopen the issue and further elaborate.
