### ISSUE TITLE
Missing Required Wayland interface

### ISSUE THREAD

**Issue by CorentinPtrl** [GhostNaN/mpvpaper#28]
When running mpvpaper -v a a i get the error '[-] Missing a required Wayland interface'.
I'm on Fedora and using XWayland

**Comment by GhostNaN** [comment]
What DE/WM are you using?
And what do you mean by XWayland? 
mpvpaper is a fully native Wayland application and isn't meant for X11 systems.

**Comment by CorentinPtrl** [comment]
Im using gnome

**Comment by GhostNaN** [comment]
Gnome is not a wlroots based Wayland compositor is not supported, sorry.

**Comment by GhostNaN** [comment]
This contains a list of wlroots Wayland based compositors if you are curious:
https://gitlab.freedesktop.org/wlroots/wlroots/-/wikis/Projects-which-use-wlroots

**Comment by CorentinPtrl** [comment]
Thanks man
