### ISSUE TITLE
Call gladLoadGLLoader() directly

### ISSUE THREAD

**Issue by asdfjkluiop** [GhostNaN/mpvpaper#3]
`gladLoadGLLoader((GLADloadproc) eglGetProcAddress)` should be called directly instead of using `gladLoadGL()`. `gladLoadGL()` internally uses the GLX loader which while not requiring an X server it does require that you have libGL installed even though in a pure wayland environment libEGL should be the only requirement for GL loading.

**Comment by GhostNaN** [comment]
Done
https://github.com/GhostNaN/mpvpaper/commit/21bb932ffb7bcd87397637c281eeb32ef92d0a6e
