### ISSUE TITLE
Add Support to Automagically pause and resume according to battery state.

### ISSUE THREAD

**Issue by tellmeY18** [GhostNaN/mpvpaper#34]
Along with the current automagic features such as auto pause and auto pause while not being used, add support to auto pause and keep the freeze frame as wallpaper when the battery is not charging. Resume when plugged in again.

**Comment by GhostNaN** [comment]
See here: https://github.com/GhostNaN/mpvpaper/issues/33

**Comment by tellmeY18** [comment]
Will try it out.
