### ISSUE TITLE
Feature request: Output of a window as the input to mpvpaper (e.g. YouTube pop out player)

### ISSUE THREAD

**Issue by ckcr4lyf** [GhostNaN/mpvpaper#40]
First of, I am a noob when it comes to compositors / wayland protocols, so I am not sure if this is even possible.

I wonder if it would be possible to take the "video output" (i.e. the window if it were fullscreen) and "pipe" it to `mpvpaper` or similar.

My use case is I play YouTube in a pop out window, it would be kinda cool if I could make one of those my desktop background.

example. of the pop out player:
![image](https://user-images.githubusercontent.com/6680615/211477221-98a1b53a-128d-490a-bf9b-5b248f53b786.png)

**Comment by GhostNaN** [comment]
I'm having a hard time understanding your request to be honest.
It sounds like you want a program's window as a background?
If that's the case, even if it is possible, it's out of scope for this project.

"mpvpaper is a wallpaper program for wlroots based wayland compositors, such as sway. That allows you to **play videos** with **mpv** as your wallpaper."

Funnily enough this question is exactly why I started this project: 
https://old.reddit.com/r/swaywm/comments/i0sdcz/is_there_a_way_to_set_a_window_as_the_background/

**Comment by ckcr4lyf** [comment]
> Funnily enough this question is exactly why I started this project:

haha, thats kinda funny. My specific use case is to play youtube as the desktop background, so I'll focus my search into passing youtube to mpv.

Thanks for this project!

**Comment by GhostNaN** [comment]
That.. I can't do. Nevermind.
