### ISSUE TITLE
(Arch x86 Hyprland nvidia-dkms-open) Background is completely black while mpv works.

### ISSUE THREAD

**Issue by Pipenguim** [GhostNaN/mpvpaper#44]
I don't really know what is going wrong. Mpvpaper shows no errors when starting the program, and I cannot find anything wrong, but the background will just not work. I tried many different files and none of them worked, and I am a bit confused. It is just a completely black screen, while CLI tells me that the video is playing.
![image](https://user-images.githubusercontent.com/70240564/229267364-0eb754b5-335e-4298-8436-f4e064693432.png)
![image](https://user-images.githubusercontent.com/70240564/229267406-dfb992a2-b9a8-408e-9892-088662c26f85.png)

**Comment by GhostNaN** [comment]
This is already a well documented issue.
Here: https://github.com/GhostNaN/mpvpaper/issues/32
And here: https://github.com/GhostNaN/mpvpaper/issues/29

**Comment by GhostNaN** [comment]
@dmadisetti

@raffaem was having this issue as well.
Are you still experiencing this raffaem from: https://github.com/GhostNaN/mpvpaper/issues/32 ?

**Comment by Pipenguim** [comment]
I fixed this by using the separate commit that you sent in one of the issues, it works perfectly.

**Comment by GhostNaN** [comment]
So you used mpvpaper from this commit: https://github.com/GhostNaN/mpvpaper/commit/f65700a3ecc9ecd8ca501e18a807ee18845f9441
Before the new render loop was created to support multiple monitor setups. 

If this issue is unsolvable, I might just bring back the old render loop as an argument to toggle.
Or just bring back the nvidia-fix branch, so people can just use that. 
It's kind of a hack for a solution, but there's not much I think I could due besides that.

**Comment by dmadisetti** [comment]
https://github.com/GhostNaN/mpvpaper/commit/f65700a3ecc9ecd8ca501e18a807ee18845f9441 works!

**Comment by GhostNaN** [comment]
> f65700a works!

I know... this is an old issue now.

I would like to see if @raffaem will respond before I do anything else.

**Comment by raffaem** [comment]
> @dmadisetti
> 
> @raffaem was having this issue as well. Are you still experiencing this raffaem from: #32 ?

No

**Comment by raffaem** [comment]
I also didn't understand what GPU and driver @Pipenguim is using

**Comment by jennydaman** [comment]
Hey, I just wanted to add another data point. I'm running Hyprland with nvidia-open-dkms, current master branch drops all frames however as previously reported https://github.com/GhostNaN/mpvpaper/commit/f65700a3ecc9ecd8ca501e18a807ee18845f9441 works for me
