### ISSUE TITLE
Mpvpaper not working 

### ISSUE THREAD

**Issue by MrDisguised** [GhostNaN/mpvpaper#46]
I installed the [`mpvpaper`](https://aur.archlinux.org/packages/mpvpaper) package from `AUR` and after running this command - 
`mpvpaper -p -f -o -loop HDMI-A-1 O1CBmbpGGVIyJAZ_4k\ konosuba\ megumin\ 60fps\ live\ wallpaper.mp4 `
It does nothing. I cannot see the video (nor hear the sound) being played. 
<br>

https://user-images.githubusercontent.com/128170542/233341451-1813bd93-1dbe-49a5-abf6-1828524c3d0e.mp4

<br>

EDIT : I tried to install the `ffnvcodec-headers` packages as mentioned in the [aur comments](https://aur.archlinux.org/packages/mpvpaper#comment-899324) but it didn't work.

**Comment by GhostNaN** [comment]
2 things

First, when you pass ```-f``` you know you're forking the process, right?
So there is no way to diagnose your issue at all when that happens.
As said in ```--help``` ```--fork         -f              Forks mpvpaper so you can close the terminal```

Second, when you pass ```-o``` please use your mpv options within quotes "".
Because mpvpaper might end up just ignoring your mpv args.
As said in ```--help``` ```--mpv-options  -o "OPTIONS"    Forwards mpv options (Must be within quotes"")```

Besides those 2 things, it looks like you might have a bad case of having a NVIDIA GPU on hyperland.
Join the club here:
https://github.com/GhostNaN/mpvpaper/issues/44
https://github.com/GhostNaN/mpvpaper/issues/38
https://github.com/GhostNaN/mpvpaper/issues/32

**Comment by MrDisguised** [comment]
> 2 things
> 
> First, when you pass `-f` you know you're forking the process, right? So there is no way to diagnose your issue at all when that happens. As said in `--help` `--fork -f Forks mpvpaper so you can close the terminal`
> 
> Second, when you pass `-o` please use your mpv options within quotes "". Because mpvpaper might end up just ignoring your mpv args. As said in `--help` `--mpv-options -o "OPTIONS" Forwards mpv options (Must be within quotes"")`
> 
> Besides those 2 things, it looks like you might have a bad case of having a NVIDIA GPU on hyperland. Join the club here: #44 #38 #32

So no workaround for this bug ?

**Comment by GhostNaN** [comment]
> So no workaround for this bug ?
EDIT : So I have to clone this repo and then I have to build the packages ?

Pretty much. 
The behavior is unpredictable on NVIDIA GPUs with the proprietary drivers, some say it works, some don't.
Despite being generally terrible, the nouveau driver works fine. So it isn't a hardware issue.

**Comment by MrDisguised** [comment]
> > So no workaround for this bug ?
> > EDIT : So I have to clone this repo and then I have to build the packages ?
> 
> Pretty much. The behavior is unpredictable on NVIDIA GPUs with the proprietary drivers, some say it works, some don't. Despite being generally terrible, the nouveau driver works fine. So it isn't a hardware issue.

Just curious how can I uninstall the package after building it ?

**Comment by MrDisguised** [comment]
@GhostNaN When I try to clone the repo I get this error - 
```
[rounak@archissexy 16:19 ~]$ git clone --single-branch https://github.com/GhostNaN/mpvpaper/tree/f65700a3ecc9ecd8ca501e18a807ee18845f9441
Cloning into 'f65700a3ecc9ecd8ca501e18a807ee18845f9441'...
fatal: repository 'https://github.com/GhostNaN/mpvpaper/tree/f65700a3ecc9ecd8ca501e18a807ee18845f9441/' not found
[rounak@archissexy 16:19 ~]$ git clone https://github.com/GhostNaN/mpvpaper/tree/f65700a3ecc9ecd8ca501e18a807ee18845f9441
Cloning into 'f65700a3ecc9ecd8ca501e18a807ee18845f9441'...
fatal: repository 'https://github.com/GhostNaN/mpvpaper/tree/f65700a3ecc9ecd8ca501e18a807ee18845f9441/' not found
[rounak@archissexy 16:19 ~]$ 
```
Bruh

**Comment by GhostNaN** [comment]
@MrDisguised You know how to use git right?

https://stackoverflow.com/questions/4114095/how-do-i-revert-a-git-repository-to-a-previous-commit

> Oh ok thanks a lot!!!! Just curious btw how can I uninstall the package after building it ?

If you used ```ninja -C build install``` then you could just delete the files from ```/usr/local/bin/``` manually.

**Comment by MrDisguised** [comment]
> @MrDisguised You know how to use git right?
> 
> https://stackoverflow.com/questions/4114095/how-do-i-revert-a-git-repository-to-a-previous-commit
> 
> > Oh ok thanks a lot!!!! Just curious btw how can I uninstall the package after building it ?
> 
> If you used `ninja -C build install` then you could just delete the files from `/usr/local/bin/` manually.

Thanks a lot!! Actually Ik nothing about git lol. I didn't read the git wiki because I don't need git.

**Comment by GhostNaN** [comment]
Please try the latest commits and compile from master.
I believe this is now solved.

**Comment by ivangeorgiew** [comment]
I'm not OP, but I had the same exact problem as him.
However now that I built with your latest changes from `master`, everything is working correctly.
Thank you!

**Comment by GhostNaN** [comment]
After the last update 1.6, this problem should be fixed now.
If this is not the case, feel free to reopen the issue.
