### ISSUE TITLE
Playlist timer

### ISSUE THREAD

**Issue by Nosirus** [GhostNaN/mpvpaper#52]
Hi,

I know it is possible for mpvpaper to play videos in a directory.
But would it be possible for it to change videos for example every hour? not just when he finishes reading one.

**Comment by GhostNaN** [comment]
Sorry for the late reply my notifications weren't posting. 
Yes, I build in this feature a while ago with the```-n, --slideshow ``` argument
So for you it would look something like this:
```mpvpaper -n 3600 HDMI-A-1 /my/video/directory```
Hope that helps.

**Comment by Nosirus** [comment]
This is exactly what I'm looking for!
Perfect remains to be seen if I can add a little transition effect

**Comment by GhostNaN** [comment]
> Perfect remains to be seen if I can add a little transition effect

Can't help you there, but I wish you luck.

**Comment by Nosirus** [comment]
Thanks
