### ISSUE TITLE
use all outputs except one

### ISSUE THREAD

**Issue by fabolous005** [GhostNaN/mpvpaper#53]
I have my ipad connected as an external display via wifi/vnc.
When mpvpaper is running the vnc connection is really slow.

Is there a possibility to specify a range of outputs so i can exclude my ipad?
Maybe just an option to exclude all headless outputs?

**Comment by GhostNaN** [comment]
Sorry for the late reply.
You couldn't before, but you should be able to now!
With this commit: https://github.com/GhostNaN/mpvpaper/commit/b677779fcbb5d662a3cc1f180f7099776e49d5fd

**Comment by fabolous005** [comment]
works like a charm thank you!
