### ISSUE TITLE
[ytdl_hook] youtube-dl failed: not found or not enough permissions  Failed to recognize file format.

### ISSUE THREAD

**Issue by Vaisakhkm2625** [GhostNaN/mpvpaper#55]
Showing error when running mpvpaper in a youtube url, but work in just mpv

https://github.com/GhostNaN/mpvpaper/assets/68694876/f89fd90c-ae40-42a2-b349-a5146621f2d4

**Comment by GhostNaN** [comment]
Works fine for me with ```yt-dlp``` installed.
But let's look at the log file:
``` mpvpaper -v -o "--log-file=output.txt" eDP-1 /my/video```

**Comment by Vaisakhkm2625** [comment]
😃 thanks.. that's was it...
when mpv worked when i ran it directly, i assumed yt-dlp was installed... 
```
~ via C via 🐍 took 29s 
❮ nix-shell -p yt-dlp mpvpaper

[nix-shell:~]$ mpvpaper eDP-1 https://www.youtube.com/watch?v=b4HI7jRqPOc
Cannot load libcuda.so.1

```

**Comment by GhostNaN** [comment]
Great to here.
Closing issue.
