### ISSUE TITLE
feature req: slideshow over all video files in a directory

### ISSUE THREAD

**Issue by nergdron** [GhostNaN/mpvpaper#56]
maybe there is an easy way to do this that I'm overlooking, but what I'd really like is to point it at a directory full of videos, and have it randomly select one to play, switching based on the setting of `--slideshow`. is there a way to do this right now?

**Comment by GhostNaN** [comment]
I don't understand. It already does that.
And you can add the "randomly" part in with ```shuffle``` added to ```--mpv-options``` like so:
```mpvpaper --slideshow 5 -o "shuffle" HDMI-A-1 /my/videos/```

**Comment by nergdron** [comment]
yep, this is what I was looking for, thanks! wasn't clear to me that would work, since the docs mostly just say "playlist", and that doesn't == "directory" to me. thanks!
