### ISSUE TITLE
Mpvpaper Drops All Frames, Only Black Output (NixOS/Hyprland)

### ISSUE THREAD

**Issue by natervader** [GhostNaN/mpvpaper#71]
`mpvpaper` consistently loads a black output regardless of the file I choose or whatever other options I test.

System info:
- AMD Ryzen 9 3900X
- NVIDIA RTX 3060
- NixOS
- Hyprland (with NVIDIA patches)
- Two displays, ViewSonic XG2701 and a Dell 1708FP

Output of `mpvpaper '*' loop.mp4 -vv`:
```
[*] Output HDMI-A-1 (Dell Inc. DELL 1708FP KU789739AACY) selected
[*] Output DP-1 (ViewSonic Corporation XG2701 SERIES 0x01010101) selected
[*] OpenGL 4.6 EGL context created
[*] Loaded [ mpv.conf ] user configs from "~/.config/mpv/"
 (+) Video --vid=1 (*) (h264 1920x1080 30.000fps)
 (+) Audio --aid=1 --alang=eng (*) (aac 2ch 48000Hz)
[*] Loaded loop.mp4
AO: [pipewire] 48000Hz stereo 2ch floatp
VO: [libmpv] 1920x1080 yuv420p
AV: 00:00:27 / 00:00:29 (94%) A-V:  0.009 Dropped: 771
[ffmpeg] NULL: missing picture in access unit with size 5
AV: 00:00:29 / 00:00:29 (100%) A-V:  0.000 Dropped: 819

[*] Exiting mpvpaper
```

Not sure what else can be mentioned from my end on the issue. I realize this can be an issue with how NixOS handles the NVIDIA drivers or simply NVIDIA's shoddy Wayland support but figured I'd report it regardless. 

Let me know if there's anything else I can add to assist in debugging!

**Comment by GhostNaN** [comment]
By the look of your verbose logs and by looking up the mpvpaper package in NixOS.
You are running a very old version of 1.3 mpvpaper!!
https://search.nixos.org/packages?channel=23.11&show=mpvpaper&from=0&size=50&sort=relevance&type=packages&query=mpvpaper

This issue was just recently fixed in version 1.6
So either compile the package from master or get someone to update the Nix package.

**Comment by GhostNaN** [comment]
I seems that it's up to date in the "unstable" repo try that:
https://search.nixos.org/packages?channel=unstable&from=0&size=50&sort=relevance&type=packages&query=mpvpaper

**Comment by natervader** [comment]
That did the trick! No kidding, never thought to check if the stable branch was that out of date. Thanks a bunch @GhostNaN.
