### ISSUE TITLE
Video is spawned on a new tiled window

### ISSUE THREAD

**Issue by CarloCattano** [GhostNaN/mpvpaper#76]
In Hyprland I have a strange behaviour ,  when launching

 mpvpaper displays the video on a new spawned window instead of in the background , and restarts every few seconds for some reason. Would like to provide more details if needed.

![20240804_10h24m51s_grim](https://github.com/user-attachments/assets/45a5527f-d995-4775-9a78-48f0219a3812)

```
mpvpaper-git r105.a445391-1
arch 6.10.2-arch1-1
hyprland-git 0.41.2.r154.ab0a3268-1
```

**Comment by GhostNaN** [comment]
I see that you are using the ```hyprland-git``` version.
I was not able to compile that from the AUR, so I can't verify if it's a new issue.
In the past this issue was because the ```--vo``` option was not ```--vo=libmpv```
But that has not been a issue for a while now.

> restarts every few seconds for some reason

You are using the ```--auto-stop -s``` flag, so I would not be surprised that the frame is stuck.
This will cause a "stopping" loop because ```--auto-stop``` stops when no new frame is created for a few seconds.
The hanging issue was a NVIDIA pro driver issue I thought I fixed, but it might be unrelated here.

> Would like to provide more details if needed.

First, please stop using the ```--fork -f``` as you won't see any messages coming from mpvpaper.
Second, I need to know what GPU you are using and the driver it's running.
Lastly, could you try ```sway``` or the stable version of ```hyprland``` to isolate the issue?

**Comment by CarloCattano** [comment]
```bash
❯ mpvpaper  -p -v -o "no-audio loop" "*" man-108056.mp4
[*] Verbose Level 1 enabled
[+] Connected to Wayland compositor
[*] OpenGL 4.6 EGL context created
[+] EGL initialized
 (+) Video --vid=1 (*) (h264 1920x1080 25.000fps)
File tags:
 Date: 2022/02/17 20:37:05
[*] Loaded man-108056.mp4
[+] MPV initialized
[*] Output eDP-1 (AU Optronics 0xD291 ) selected
VO: [gpu] 1920x1080 yuv420p
V: 00:00:03 / 00:00:25 (15%)[*] Pausing because mpvpaper is hidden
(Paused) V: 00:00:03 / 00:00:25 (15%)
```

It could be related to nvidia, its a laptop

```
VIDIA-SMI 555.58.02              Driver Version: 555.58.02      CUDA Version: 12.5
NVIDIA T550 Laptop GPU (dedicated)
Intel Corporation Alder Lake-P GT2 [Iris Xe Graphics] (dedicated)

I will try with installing sway and report back

**Comment by CarloCattano** [comment]
Same behavior in Sway am afraid

**Comment by GhostNaN** [comment]
Odd, what's in your mpv config settings?
To isolate the config try running mpvpaper with:
```mpvpaper -o "config=no" "*" man-108056.mp4```

**Comment by CarloCattano** [comment]
Interesting, I never had a config file for mpvpaper. However , running your suggested command the difference is that the video continues to play normally, instead of 
```V: 00:00:03 / 00:00:25 (15%)[*] Pausing because mpvpaper is hidden```
like with my command

**Comment by GhostNaN** [comment]
So it works completely fine and running in the back without the config?

**Comment by CarloCattano** [comment]
Oh no, it's the same bug but the video keeps playing instead of pausing claiming to be hidden in it's new tiled window

**Comment by GhostNaN** [comment]
BTW the ```--auto-pause``` and ```--auto-stop``` don't even seem to work on hyprland as intended.
They were always just a hack that sort of worked for sway.
So I would not even bother with those options again and just use the "watch lists" instead.
You could look at the man page to learn about these "watch lists".

> it's new tiled window

I just don't see how that's possible unless you are somehow running an older version of mpvpaper.
How about setting the ```--vo``` like I mentioned before:
```mpvpaper -o "--vo=libmpv" "*" man-108056.mp4```

**Comment by CarloCattano** [comment]
ok that was the issue , simply adding ```-o "--vo=libmpv"``` fixes it , thankyou !
