### ISSUE TITLE
how to make MPVPaper been ignore in mpris in waybar 

### ISSUE THREAD

**Issue by matrix543** [GhostNaN/mpvpaper#79]
trying to figure out how to make mpris module in waybar ignore mpvpaper but still be able to control regular mpv anyone else having this issue

not sure if this have to do with mpvpaper or more a waybar mpris module problem

**Comment by GhostNaN** [comment]
I don't think there is anything that can be done on the mpvpaper side of things.
Because of course mpvpaper uses mpv to run the videos.
So I assume this is something waybar-mpris will have to implement to avoid this issue.

**Comment by oblivioneater** [comment]
I think you might be omitting some information here, MPV does not support MPRIS by default. Are you using a plugin like mpv-mpris? If so, you can just disable it by passing `-o "load-scripts=no"` to mpvpaper. This will disable ALL of your plugins though.

**Comment by matrix543** [comment]
That make it worked i use jakoolit dots file for waybar in his modules file its a section called mpris that you can use in the bar config
