### ISSUE TITLE
Disabling subtitles

### ISSUE THREAD

**Issue by jvarelaw** [GhostNaN/mpvpaper#86]
Can I disable subtitles for mpvpaper? If I can, how? And if i can't, there's any other way? Or how do I can directly remove every subtitles from around 40 different videos divided in two folders?

My actual commands used in my custom conf file to exec mpvpaper everytime my pc starts are the following:

```
# Load the first wallpaper

exec-once = mpvpaper -vf -o "no-audio --loop-playlist shuffle" eDP-1 /home/soma/Vídeos/eDP-1

# Load the second wallpaper
exec-once = mpvpaper -vf -o "no-audio --loop-playlist shuffle" HDMI-A-1 /home/soma/Vídeos/HDMI-1-A-1
```

**Comment by GhostNaN** [comment]
https://mpv.io/manual/stable/#options-sid
```-- sid=no```

```mpvpaper -vf -o "no-audio loop-playlist shuffle sid=no" eDP-1 /home/soma/Vídeos/eDP-1```
