### ISSUE TITLE
Changing video for specific monitor without previous still running

### ISSUE THREAD

**Issue by anufrievroman** [GhostNaN/mpvpaper#88]
Hello, we are trying to [implement mpvpaper support in waypaper](https://github.com/anufrievroman/waypaper/issues/12), and we are facing an issue of changing wallpaper for specific monitor in such a way that previous video would stop running. I checked the documentations, but couldn't really find an answer, maybe you could help us?

Let me explain with an example: we set one video for one monitor, then we set another video for another monitor, then we want to change again for the first monitor, but if we do so, previous video keeps running on the background. Would you suggest any way to keep track of which process is running on which monitor? It would be ideal if it was on the side of mpvpaper (like all other wallpaper daemons) to track its processes and kill/update them when new wallpaper is allocated to the same output.

Sorry if I missed something.

**Comment by GhostNaN** [comment]
> Would you suggest any way to keep track of which process is running on which monitor?

Can't you just get the returned variable from ```subprocess.Popen(command)``` and track that, then kill it later?

>It would be ideal if it was on the side of mpvpaper (like all other wallpaper daemons) to track its processes and kill/update them when new wallpaper is allocated to the same output.

I saw no point in making mpvpaper a daemon.
It's kind of a pain with all the initialization with mpv just to play a new video on a separate monitor.
And any modifications while playing can be done with a mpv input-ipc-server socket.

> I think maybe the mpvpaper process needs to be "forked" and then controlled as mpvpaper -o "input-ipc-server=/tmp/mpv-socket" DP-1 /path/to/video, I'll try tomorrow..


I believe you are on the right track here.

**Comment by anufrievroman** [comment]
Thank you for quick response! I can't really track and kill processes via python because the program can be closed and opened many times while some wallpaper is running. So, I'm trying to work in the direction of the control via the socket. However, at the moment, my attempts to control the already playing video in the socket just creates new processes, maybe I'm doing something wrong. But, in general, issuing a new video with a new command into the same socket should start playing the new video using the already existing process, right? 

p.s. If you don't mind, I'll keep the issue for a little while to ask further questions.

**Comment by GhostNaN** [comment]
> However, at the moment, my attempts to control the already playing video in the socket just creates new processes, maybe I'm doing something wrong. But, in general, issuing a new video with a new command into the same socket should start playing the new video using the already existing process, right?

I seriously don't understand why controlling the socket is causing new instances of mpvpaper to appear.
And yes, as long as the process is still running it can be controlled by the socket passed from ```input-ipc-server=```
Let me provide a simple example that applies to your situation.

It's best to name your socket with an original name, in this case, the output name:
```mpvpaper -o " input-ipc-server=/tmp/mpv-socket-DP-3 loop" DP-3 /my/video.mp4```

Then just like it's mention in the man page you can send a command to the socket with socat.
Here I assumed you just want to let the user load a new video:
```echo 'loadfile /my/new_video.mp4 ' | socat - /tmp/mpv-socket-DP-3```

The only new process that needs to spin up at all is to run the socat command to the socket file in question.
But I imagine that's not much of a concern.

**Comment by GhostNaN** [comment]
And of course if you rather use something other than ```socat``` to send the commands,
I'm sure there is something in python nativly to help with that.

**Comment by anufrievroman** [comment]
Ah, I see, I misuderstood the man page that we can just issue several `mpvpaper -o " input-..." commands to the same socket. Thanks a lot, now it works! I'll close the issue then. Thank you for the explanation.
